version:
  "3"
services:
  database:
    image: mysql:8.0.31
    container_name: database
    environment:
      MYSQL_DATABASE: coupon
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: dlalstjr1!
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    restart: always

  application1:
    image : minseokey/coupon:0.1
    depends_on:
      - database
      - redis
    container_name: application1
    restart: always
    ports:
     - "8081:8080"
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/coupon?serverTimezone=Asia/Seoul
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_PASSWORD: dlalstjr1!
     REDIS_HOST: redis
     TZ: "Asia/Seoul"

  application2:
    image : minseokey/coupon:0.1
    depends_on:
      - database
      - redis
    container_name: application2
    restart: always
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/coupon?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dlalstjr1!
      REDIS_HOST: redis
      TZ: "Asia/Seoul"

  application3:
    image : minseokey/coupon:0.1
    depends_on:
      - database
      - redis
    container_name: application3
    restart: always
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/coupon?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dlalstjr1!
      REDIS_HOST: redis
      TZ: "Asia/Seoul"

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    environment:
        TZ: "Asia/Seoul"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - application1
      - application2
      - application3
    restart: always
    environment:
        TZ: "Asia/Seoul"